version: "3"
services:
    php:
        image: $APP_IMAGE
        volumes:
            - ./:/app
        container_name: ${SERVICE_NAME}_php

    nginx:
        image: nginx:latest
        ports:
            - 127.0.0.1:${NGINX_PORT}:80
        volumes:
            - .:/app:cached
            - ./docker/nginx/templates:/etc/nginx/templates
        container_name: ${SERVICE_NAME}_nginx
        env_file:
            - ./.env
        depends_on:
            - php

    mysql:
        image: mysql:5.7
        volumes:
            - ./docker/mysql/data:/var/lib/mysql:cached
        ports:
            - 127.0.0.1:${MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DB_NAME: ${MYSQL_DB_NAME}
        container_name: ${SERVICE_NAME}_mysql